const pokemonData = [
  {
    id: 1,
    name: "Bulbasaur",
    "evolution-line": ["Bulbasaur", "Ivysaur", "Venusaur"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0001Bulbasaur.png",
  },
  {
    id: 2,
    name: "Ivysaur",
    "evolution-line": ["Bulbasaur", "Ivysaur", "Venusaur"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0002Ivysaur.png",
  },
  {
    id: 3,
    name: "Venusaur",
    "evolution-line": ["Bulbasaur", "Ivysaur", "Venusaur"],
    isEvovable: false,
    type: "grass",
    path: "./pokemon-images/250px-0003Venusaur.png",
  },
  {
    id: 4,
    name: "Charmander",
    "evolution-line": ["Charmander", "Charmeleon", "Charizard"],
    isEvovable: true,
    type: "fire",
    path: "./pokemon-images/250px-0004Charmander.png",
  },
  {
    id: 5,
    name: "Charmeleon",
    "evolution-line": ["Charmander", "Charmeleon", "Charizard"],
    isEvovable: true,
    type: "fire",
    path: "./pokemon-images/250px-0005Charmeleon.png",
  },
  {
    id: 6,
    name: "Charizard",
    "evolution-line": ["Charmander", "Charmeleon", "Charizard"],
    isEvovable: false,
    type: "fire",
    path: "./pokemon-images/250px-0006Charizard.png",
  },
  {
    id: 7,
    name: "Squirtle",
    "evolution-line": ["Squirtle", "Wartortle", "Blastoise"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0007Squirtle.png",
  },
  {
    id: 8,
    name: "Wartortle",
    "evolution-line": ["Squirtle", "Wartortle", "Blastoise"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0008Wartortle.png",
  },
  {
    id: 9,
    name: "Blastoise",
    "evolution-line": ["Squirtle", "Wartortle", "Blastoise"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0009Blastoise.png",
  },
  {
    id: 10,
    name: "Caterpie",
    "evolution-line": ["Caterpie", "Metapod", "Butterfree"],
    isEvovable: true,
    type: "bug",
    path: "./pokemon-images/250px-0010Caterpie.png",
  },
  {
    id: 11,
    name: "Metapod",
    "evolution-line": ["Caterpie", "Metapod", "Butterfree"],
    isEvovable: true,
    type: "bug",
    path: "./pokemon-images/250px-0011Metapod.png",
  },
  {
    id: 12,
    name: "Butterfree",
    "evolution-line": ["Caterpie", "Metapod", "Butterfree"],
    isEvovable: false,
    type: "bug",
    path: "./pokemon-images/250px-0012Butterfree.png",
  },
  {
    id: 13,
    name: "Weedle",
    "evolution-line": ["Weedle", "Kakuna", "Beedrill"],
    isEvovable: true,
    type: "bug",
    path: "./pokemon-images/250px-0013Weedle.png",
  },
  {
    id: 14,
    name: "Kakuna",
    "evolution-line": ["Weedle", "Kakuna", "Beedrill"],
    isEvovable: true,
    type: "bug",
    path: "./pokemon-images/250px-0014Kakuna.png",
  },
  {
    id: 15,
    name: "Beedrill",
    "evolution-line": ["Weedle", "Kakuna", "Beedrill"],
    isEvovable: false,
    type: "bug",
    path: "./pokemon-images/250px-0015Beedrill.png",
  },
  {
    id: 16,
    name: "Pidgey",
    "evolution-line": ["Pidgey", "Pidgeotto", "Pidgeot"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0016Pidgey.png",
  },
  {
    id: 17,
    name: "Pidgeotto",
    "evolution-line": ["Pidgey", "Pidgeotto", "Pidgeot"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0017Pidgeotto.png",
  },
  {
    id: 18,
    name: "Pidgeot",
    "evolution-line": ["Pidgey", "Pidgeotto", "Pidgeot"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0018Pidgeot.png",
  },
  {
    id: 19,
    name: "Rattata",
    "evolution-line": ["Rattata", "Raticate"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0019Rattata.png",
  },
  {
    id: 20,
    name: "Raticate",
    "evolution-line": ["Rattata", "Raticate"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0020Raticate.png",
  },
  {
    id: 21,
    name: "Spearow",
    "evolution-line": ["Spearow", "Fearow"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0021Spearow.png",
  },
  {
    id: 22,
    name: "Fearow",
    "evolution-line": ["Spearow", "Fearow"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0022Fearow.png",
  },
  {
    id: 23,
    name: "Ekans",
    "evolution-line": ["Ekans", "Arbok"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0023Ekans.png",
  },
  {
    id: 24,
    name: "Arbok",
    "evolution-line": ["Ekans", "Arbok"],
    isEvovable: false,
    type: "poison",
    path: "./pokemon-images/250px-0024Arbok.png",
  },
  {
    id: 25,
    name: "Pikachu",
    "evolution-line": ["Pichu", "Pikachu", "Raichu"],
    isEvovable: true,
    type: "electric",
    path: "./pokemon-images/250px-0025Pikachu.png",
  },
  {
    id: 26,
    name: "Raichu",
    "evolution-line": ["Pikachu", "Raichu"],
    isEvovable: false,
    type: "electric",
    path: "./pokemon-images/250px-0026Raichu.png",
  },
  {
    id: 27,
    name: "Sandshrew",
    "evolution-line": ["Sandshrew", "Sandslash"],
    isEvovable: true,
    type: "ground",
    path: "./pokemon-images/250px-0027Sandshrew.png",
  },
  {
    id: 28,
    name: "Sandslash",
    "evolution-line": ["Sandshrew", "Sandslash"],
    isEvovable: false,
    type: "ground",
    path: "./pokemon-images/250px-0028Sandslash.png",
  },
  {
    id: 29,
    name: "Nidoran ♀",
    "evolution-line": ["Nidoran ♀", "Nidorina", "Nidoqueen"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0029Nidoran.png",
  },
  {
    id: 30,
    name: "Nidorina",
    "evolution-line": ["Nidoran♀", "Nidorina", "Nidoqueen"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0030Nidorina.png",
  },
  {
    id: 31,
    name: "Nidoqueen",
    "evolution-line": ["Nidoran♀", "Nidorina", "Nidoqueen"],
    isEvovable: false,
    type: "poison",
    path: "./pokemon-images/250px-0031Nidoqueen.png",
  },
  {
    id: 32,
    name: "Nidoran ♂",
    "evolution-line": ["Nidoran ♂", "Nidorino", "Nidoking"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0032Nidoran.png",
  },
  {
    id: 33,
    name: "Nidorino",
    "evolution-line": ["Nidoran ♂", "Nidorino", "Nidoking"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0033Nidorino.png",
  },
  {
    id: 34,
    name: "Nidoking",
    "evolution-line": ["Nidoran ♂", "Nidorino", "Nidoking"],
    isEvovable: false,
    type: "poison",
    path: "./pokemon-images/250px-0034Nidoking.png",
  },
  {
    id: 35,
    name: "Clefairy",
    "evolution-line": ["Cleffa", "Clefairy", "Clefable"],
    isEvovable: true,
    type: "fairy",
    path: "./pokemon-images/250px-0035Clefairy.png",
  },
  {
    id: 36,
    name: "Clefable",
    "evolution-line": ["Cleffa", "Clefairy", "Clefable"],
    isEvovable: false,
    type: "fairy",
    path: "./pokemon-images/250px-0036Clefable.png",
  },
  {
    id: 37,
    name: "Vulpix",
    "evolution-line": ["Vulpix", "Ninetales"],
    isEvovable: true,
    type: "fire",
    path: "./pokemon-images/250px-0037Vulpix.png",
  },
  {
    id: 38,
    name: "Ninetales",
    "evolution-line": ["Vulpix", "Ninetales"],
    isEvovable: false,
    type: "fire",
    path: "./pokemon-images/250px-0038Ninetales.png",
  },
  {
    id: 39,
    name: "Jigglypuff",
    "evolution-line": ["Igglybuff", "Jigglypuff", "Wigglytuff"],
    isEvovable: true,
    type: "fairy",
    path: "./pokemon-images/250px-0039Jigglypuff.png",
  },
  {
    id: 40,
    name: "Wigglytuff",
    "evolution-line": ["Igglybuff", "Jigglypuff", "Wigglytuff"],
    isEvovable: false,
    type: "fairy",
    path: "./pokemon-images/250px-0040Wigglytuff.png",
  },
  {
    id: 41,
    name: "Zubat",
    "evolution-line": ["Zubat", "Golbat"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0041Zubat.png",
  },
  {
    id: 42,
    name: "Golbat",
    "evolution-line": ["Zubat", "Golbat", "Crobat"],
    isEvovable: false,
    type: "poison",
    path: "./pokemon-images/250px-0042Golbat.png",
  },
  {
    id: 43,
    name: "Oddish",
    "evolution-line": ["Oddish", "Gloom", "Vileplume"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0043Oddish.png",
  },
  {
    id: 44,
    name: "Gloom",
    "evolution-line": ["Oddish", "Gloom", "Vileplume"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0044Gloom.png",
  },
  {
    id: 45,
    name: "Vileplume",
    "evolution-line": ["Gloom", "Vileplume"],
    isEvovable: false,
    type: "grass",
    path: "./pokemon-images/250px-0045Vileplume.png",
  },
  {
    id: 46,
    name: "Paras",
    "evolution-line": ["Paras", "Parasect"],
    isEvovable: true,
    type: "bug",
    path: "./pokemon-images/250px-0046Paras.png",
  },
  {
    id: 47,
    name: "Parasect",
    "evolution-line": ["Paras", "Parasect"],
    isEvovable: false,
    type: "bug",
    path: "./pokemon-images/250px-0047Parasect.png",
  },
  {
    id: 48,
    name: "Venonat",
    "evolution-line": ["Venonat", "Venomoth"],
    isEvovable: true,
    type: "bug",
    path: "./pokemon-images/250px-0048Venonat.png",
  },
  {
    id: 49,
    name: "Venomoth",
    "evolution-line": ["Venonat", "Venomoth"],
    isEvovable: false,
    type: "bug",
    path: "./pokemon-images/250px-0049Venomoth.png",
  },
  {
    id: 50,
    name: "Diglett",
    "evolution-line": ["Diglett", "Dugtrio"],
    isEvovable: true,
    type: "ground",
    path: "./pokemon-images/250px-0050Diglett.png",
  },
  {
    id: 51,
    name: "Dugtrio",
    "evolution-line": ["Diglett", "Dugtrio"],
    isEvovable: false,
    type: "ground",
    path: "./pokemon-images/250px-0051Dugtrio.png",
  },
  {
    id: 52,
    name: "Meowth",
    "evolution-line": ["Meowth", "Persian"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0052Meowth.png",
  },
  {
    id: 53,
    name: "Persian",
    "evolution-line": ["Meowth", "Persian"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0053Persian.png",
  },
  {
    id: 54,
    name: "Psyduck",
    "evolution-line": ["Psyduck", "Golduck"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0054Psyduck.png",
  },
  {
    id: 55,
    name: "Golduck",
    "evolution-line": ["Psyduck", "Golduck"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0055Golduck.png",
  },
  {
    id: 56,
    name: "Mankey",
    "evolution-line": ["Mankey", "Primeape"],
    isEvovable: true,
    type: "fighting",
    path: "./pokemon-images/250px-0056Mankey.png",
  },
  {
    id: 57,
    name: "Primeape",
    "evolution-line": ["Mankey", "Primeape"],
    isEvovable: false,
    type: "fighting",
    path: "./pokemon-images/250px-0057Primeape.png",
  },
  {
    id: 58,
    name: "Growlithe",
    "evolution-line": ["Growlithe", "Arcanine"],
    isEvovable: true,
    type: "fire",
    path: "./pokemon-images/250px-0058Growlithe.png",
  },
  {
    id: 59,
    name: "Arcanine",
    "evolution-line": ["Growlithe", "Arcanine"],
    isEvovable: false,
    type: "fire",
    path: "./pokemon-images/250px-0059Arcanine.png",
  },
  {
    id: 60,
    name: "Poliwag",
    "evolution-line": ["Poliwag", "Poliwhirl"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0060Poliwag.png",
  },
  {
    id: 61,
    name: "Poliwhirl",
    "evolution-line": ["Poliwag", "Poliwhirl", "Poliwrath"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0061Poliwhirl.png",
  },
  {
    id: 62,
    name: "Poliwrath",
    "evolution-line": ["Poliwag", "Poliwhirl", "Poliwrath"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0062Poliwrath.png",
  },
  {
    id: 63,
    name: "Abra",
    "evolution-line": ["Abra", "Kadabra"],
    isEvovable: true,
    type: "psychic",
    path: "./pokemon-images/250px-0063Abra.png",
  },
  {
    id: 64,
    name: "Kadabra",
    "evolution-line": ["Abra", "Kadabra", "Alakazam"],
    isEvovable: true,
    type: "psychic",
    path: "./pokemon-images/250px-0064Kadabra.png",
  },
  {
    id: 65,
    name: "Alakazam",
    "evolution-line": ["Abra", "Kadabra", "Alakazam"],
    isEvovable: false,
    type: "psychic",
    path: "./pokemon-images/250px-0065Alakazam.png",
  },
  {
    id: 66,
    name: "Machop",
    "evolution-line": ["Machop", "Machoke"],
    isEvovable: true,
    type: "fighting",
    path: "./pokemon-images/250px-0066Machop.png",
  },
  {
    id: 67,
    name: "Machoke",
    "evolution-line": ["Machop", "Machoke", "Machamp"],
    isEvovable: true,
    type: "fighting",
    path: "./pokemon-images/250px-0067Machoke.png",
  },
  {
    id: 68,
    name: "Machamp",
    "evolution-line": ["Machop", "Machoke", "Machamp"],
    isEvovable: false,
    type: "fighting",
    path: "./pokemon-images/250px-0068Machamp.png",
  },
  {
    id: 69,
    name: "Bellsprout",
    "evolution-line": ["Bellsprout", "Weepinbell"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0069Bellsprout.png",
  },
  {
    id: 70,
    name: "Weepinbell",
    "evolution-line": ["Bellsprout", "Weepinbell", "Victreebel"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0070Weepinbell.png",
  },
  {
    id: 71,
    name: "Victreebel",
    "evolution-line": ["Bellsprout", "Weepinbell", "Victreebel"],
    isEvovable: false,
    type: "grass",
    path: "./pokemon-images/250px-0071Victreebel.png",
  },
  {
    id: 72,
    name: "Tentacool",
    "evolution-line": ["Tentacool", "Tentacruel"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0072Tentacool.png",
  },
  {
    id: 73,
    name: "Tentacruel",
    "evolution-line": ["Tentacool", "Tentacruel"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0073Tentacruel.png",
  },
  {
    id: 74,
    name: "Geodude",
    "evolution-line": ["Geodude", "Graveler"],
    isEvovable: true,
    type: "rock",
    path: "./pokemon-images/250px-0074Geodude.png",
  },
  {
    id: 75,
    name: "Graveler",
    "evolution-line": ["Geodude", "Graveler", "Golem"],
    isEvovable: true,
    type: "rock",
    path: "./pokemon-images/250px-0075Graveler.png",
  },
  {
    id: 76,
    name: "Golem",
    "evolution-line": ["Geodude", "Graveler", "Golem"],
    isEvovable: false,
    type: "rock",
    path: "./pokemon-images/250px-0076Golem.png",
  },
  {
    id: 77,
    name: "Ponyta",
    "evolution-line": ["Ponyta", "Rapidash"],
    isEvovable: true,
    type: "fire",
    path: "./pokemon-images/250px-0077Ponyta.png",
  },
  {
    id: 78,
    name: "Rapidash",
    "evolution-line": ["Ponyta", "Rapidash"],
    isEvovable: false,
    type: "fire",
    path: "./pokemon-images/250px-0078Rapidash.png",
  },
  {
    id: 79,
    name: "Slowpoke",
    "evolution-line": ["Slowpoke", "Slowbro"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0079Slowpoke.png",
  },
  {
    id: 80,
    name: "Slowbro",
    "evolution-line": ["Slowpoke", "Slowbro"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0080Slowbro.png",
  },
  {
    id: 81,
    name: "Magnemite",
    "evolution-line": ["Magnemite", "Magneton"],
    isEvovable: true,
    type: "electric",
    path: "./pokemon-images/250px-0081Magnemite.png",
  },
  {
    id: 82,
    name: "Magneton",
    "evolution-line": ["Magnemite", "Magneton"],
    isEvovable: false,
    type: "electric",
    path: "./pokemon-images/250px-0082Magneton.png",
  },
  {
    id: 83,
    name: "Farfetch'd",
    "evolution-line": ["Farfetch'd"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0083Farfetch'd.png",
  },
  {
    id: 84,
    name: "Doduo",
    "evolution-line": ["Doduo", "Dodrio"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0084Doduo.png",
  },
  {
    id: 85,
    name: "Dodrio",
    "evolution-line": ["Doduo", "Dodrio"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0085Dodrio.png",
  },
  {
    id: 86,
    name: "Seel",
    "evolution-line": ["Seel", "Dewgong"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0086Seel.png",
  },
  {
    id: 87,
    name: "Dewgong",
    "evolution-line": ["Seel", "Dewgong"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0087Dewgong.png",
  },
  {
    id: 88,
    name: "Grimer",
    "evolution-line": ["Grimer", "Muk"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0088Grimer.png",
  },
  {
    id: 89,
    name: "Muk",
    "evolution-line": ["Grimer", "Muk"],
    isEvovable: false,
    type: "poison",
    path: "./pokemon-images/250px-0089Muk.png",
  },
  {
    id: 90,
    name: "Shellder",
    "evolution-line": ["Shellder", "Cloyster"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0090Shellder.png",
  },
  {
    id: 91,
    name: "Cloyster",
    "evolution-line": ["Shellder", "Cloyster"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0091Cloyster.png",
  },
  {
    id: 92,
    name: "Gastly",
    "evolution-line": ["Gastly", "Haunter", "Gengar"],
    isEvovable: true,
    type: "ghost",
    path: "./pokemon-images/250px-0092Gastly.png",
  },
  {
    id: 93,
    name: "Haunter",
    "evolution-line": ["Gastly", "Haunter", "Gengar"],
    isEvovable: true,
    type: "ghost",
    path: "./pokemon-images/250px-0093Haunter.png",
  },
  {
    id: 94,
    name: "Gengar",
    "evolution-line": ["Gastly", "Haunter", "Gengar"],
    isEvovable: false,
    type: "ghost",
    path: "./pokemon-images/250px-0094Gengar.png",
  },
  {
    id: 95,
    name: "Onix",
    "evolution-line": ["Onix"],
    isEvovable: false,
    type: "rock",
    path: "./pokemon-images/250px-0095Onix.png",
  },
  {
    id: 96,
    name: "Drowzee",
    "evolution-line": ["Drowzee", "Hypno"],
    isEvovable: true,
    type: "psychic",
    path: "./pokemon-images/250px-0096Drowzee.png",
  },
  {
    id: 97,
    name: "Hypno",
    "evolution-line": ["Drowzee", "Hypno"],
    isEvovable: false,
    type: "psychic",
    path: "./pokemon-images/250px-0097Hypno.png",
  },
  {
    id: 98,
    name: "Krabby",
    "evolution-line": ["Krabby", "Krignler"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0098Krabby.png",
  },
  {
    id: 99,
    name: "Kringler",
    "evolution-line": ["Krabby", "Kringler"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0099Kingler.png",
  },
  {
    id: 100,
    name: "Voltorb",
    "evolution-line": ["Voltorb", "Electrode"],
    isEvovable: true,
    type: "electric",
    path: "./pokemon-images/250px-0100Voltorb.png",
  },
  {
    id: 101,
    name: "Electrode",
    "evolution-line": ["Voltorb", "Electrode"],
    isEvovable: false,
    type: "electric",
    path: "./pokemon-images/250px-0101Electrode.png",
  },
  {
    id: 102,
    name: "Exeggcute",
    "evolution-line": ["Exeggcute", "Exeggutor"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0102Exeggcute.png",
  },
  {
    id: 103,
    name: "Exeggutor",
    "evolution-line": ["Exeggcute", "Exeggutor"],
    isEvovable: false,
    type: "grass",
    path: "./pokemon-images/250px-0103Exeggutor.png",
  },
  {
    id: 104,
    name: "Cubone",
    "evolution-line": ["Cubone", "Marowak"],
    isEvovable: true,
    type: "ground",
    path: "./pokemon-images/250px-0104Cubone.png",
  },
  {
    id: 105,
    name: "Marowak",
    "evolution-line": ["Cubone", "Marowak"],
    isEvovable: false,
    type: "ground",
    path: "./pokemon-images/250px-0105Marowak.png",
  },
  {
    id: 106,
    name: "Hitmonlee",
    "evolution-line": ["Hitmonlee"],
    isEvovable: false,
    type: "fighting",
    path: "./pokemon-images/250px-0106Hitmonlee.png",
  },
  {
    id: 107,
    name: "Hitmonchan",
    "evolution-line": ["Hitmonchan"],
    isEvovable: false,
    type: "fighting",
    path: "./pokemon-images/250px-0107Hitmonchan.png",
  },
  {
    id: 108,
    name: "Lickitung",
    "evolution-line": ["Lickitung"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0108Lickitung.png",
  },
  {
    id: 109,
    name: "Koffing",
    "evolution-line": ["Koffing", "Weezing"],
    isEvovable: true,
    type: "poison",
    path: "./pokemon-images/250px-0109Koffing.png",
  },
  {
    id: 110,
    name: "Weezing",
    "evolution-line": ["Koffing", "Weezing"],
    isEvovable: false,
    type: "poison",
    path: "./pokemon-images/250px-0110Weezing.png",
  },
  {
    id: 111,
    name: "Rhyhorn",
    "evolution-line": ["Rhyhorn", "Rhydon"],
    isEvovable: true,
    type: "rock",
    path: "./pokemon-images/250px-0111Rhyhorn.png",
  },
  {
    id: 112,
    name: "Rhydon",
    "evolution-line": ["Rhyhorn", "Rhydon"],
    isEvovable: false,
    type: "rock",
    path: "./pokemon-images/250px-0112Rhydon.png",
  },
  {
    id: 113,
    name: "Chansey",
    "evolution-line": ["Chansey", "Blissey"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0113Chansey.png",
  },
  {
    id: 114,
    name: "Tangela",
    "evolution-line": ["Tangela", "Tangrowth"],
    isEvovable: true,
    type: "grass",
    path: "./pokemon-images/250px-0114Tangela.png",
  },
  {
    id: 115,
    name: "Kangaskhan",
    "evolution-line": ["Kangaskhan"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0115Kangaskhan.png",
  },
  {
    id: 116,
    name: "Horsea",
    "evolution-line": ["Horsea", "Seadra"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0116Horsea.png",
  },
  {
    id: 117,
    name: "Seadra",
    "evolution-line": ["Horsea", "Seadra"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0117Seadra.png",
  },
  {
    id: 118,
    name: "Goldeen",
    "evolution-line": ["Goldeen", "Seaking"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0118Goldeen.png",
  },
  {
    id: 119,
    name: "Seaking",
    "evolution-line": ["Goldeen", "Seaking"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0119Seaking.png",
  },
  {
    id: 120,
    name: "Staryu",
    "evolution-line": ["Staryu", "Starmie"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0120Staryu.png",
  },

  {
    id: 121,
    name: "Starmie",
    "evolution-line": ["Staryu", "Starmie"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0121Starmie.png",
  },
  {
    id: 122,
    name: "Mr. Mime",
    "evolution-line": ["Mr. Mime"],
    isEvovable: false,
    type: "psychic",
    path: "./pokemon-images/250px-0122Mr._Mime.png",
  },
  {
    id: 123,
    name: "Scyther",
    "evolution-line": ["Scyther"],
    isEvovable: false,
    type: "bug",
    path: "./pokemon-images/250px-0123Scyther.png",
  },
  {
    id: 124,
    name: "Jynx",
    "evolution-line": ["Jynx"],
    isEvovable: false,
    type: "ice",
    path: "./pokemon-images/250px-0124Jynx.png",
  },
  {
    id: 125,
    name: "Electabuzz",
    "evolution-line": ["Electabuzz"],
    isEvovable: false,
    type: "electric",
    path: "./pokemon-images/250px-0125Electabuzz.png",
  },
  {
    id: 126,
    name: "Magmar",
    "evolution-line": ["Magmar"],
    isEvovable: false,
    type: "fire",
    path: "./pokemon-images/250px-0126Magmar.png",
  },
  {
    id: 127,
    name: "Pinsir",
    "evolution-line": ["Pinsir"],
    isEvovable: false,
    type: "bug",
    path: "./pokemon-images/250px-0127Pinsir.png",
  },
  {
    id: 128,
    name: "Tauros",
    "evolution-line": ["Tauros"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0128Tauros.png",
  },
  {
    id: 129,
    name: "Magikarp",
    "evolution-line": ["Magikarp", "Gyarados"],
    isEvovable: true,
    type: "water",
    path: "./pokemon-images/250px-0129Magikarp.png",
  },
  {
    id: 130,
    name: "Gyarados",
    "evolution-line": ["Magikarp", "Gyarados"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0130Gyarados.png",
  },
  {
    id: 131,
    name: "Lapras",
    "evolution-line": ["Lapras"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0131Lapras.png",
  },
  {
    id: 132,
    name: "Ditto",
    "evolution-line": ["Ditto"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0132Ditto.png",
  },
  {
    id: 133,
    name: "Eevee",
    "evolution-line": ["Eevee", "Vaporeon"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0133Eevee.png",
  },
  {
    id: 134,
    name: "Vaporeon",
    "evolution-line": ["Eevee", "Vaporeon"],
    isEvovable: false,
    type: "water",
    path: "./pokemon-images/250px-0134Vaporeon.png",
  },
  {
    id: 135,
    name: "Jolteon",
    "evolution-line": ["Eevee", "Jolteon"],
    isEvovable: false,
    type: "electric",
    path: "./pokemon-images/250px-0135Jolteon.png",
  },
  {
    id: 136,
    name: "Flareon",
    "evolution-line": ["Eevee", "Flareon"],
    isEvovable: false,
    type: "fire",
    path: "./pokemon-images/250px-0136Flareon.png",
  },
  {
    id: 137,
    name: "Porygon",
    "evolution-line": ["Porygon", "Porygon2"],
    isEvovable: true,
    type: "normal",
    path: "./pokemon-images/250px-0137Porygon.png",
  },
  {
    id: 138,
    name: "Omanyte",
    "evolution-line": ["Omanyte", "Omastar"],
    isEvovable: true,
    type: "rock",
    path: "./pokemon-images/250px-0138Omanyte.png",
  },
  {
    id: 139,
    name: "Omastar",
    "evolution-line": ["Omanyte", "Omastar"],
    isEvovable: false,
    type: "rock",
    path: "./pokemon-images/250px-0139Omastar.png",
  },
  {
    id: 140,
    name: "Kabuto",
    "evolution-line": ["Kabuto", "Kabutops"],
    isEvovable: true,
    type: "rock",
    path: "./pokemon-images/250px-0140Kabuto.png",
  },
  {
    id: 141,
    name: "Kabutops",
    "evolution-line": ["Kabuto", "Kabutops"],
    isEvovable: false,
    type: "rock",
    path: "./pokemon-images/250px-0141Kabutops.png",
  },
  {
    id: 142,
    name: "Aerodactyl",
    "evolution-line": ["Aerodactyl"],
    isEvovable: false,
    type: "rock",
    path: "./pokemon-images/250px-0142Aerodactyl.png",
  },
  {
    id: 143,
    name: "Snorlax",
    "evolution-line": ["Snorlax"],
    isEvovable: false,
    type: "normal",
    path: "./pokemon-images/250px-0143Snorlax.png",
  },
  {
    id: 144,
    name: "Articuno",
    "evolution-line": ["Articuno"],
    isEvovable: false,
    type: "ice",
    path: "./pokemon-images/250px-0144Articuno.png",
  },
  {
    id: 145,
    name: "Zapdos",
    "evolution-line": ["Zapdos"],
    isEvovable: false,
    type: "electric",
    path: "./pokemon-images/250px-0145Zapdos.png",
  },
  {
    id: 146,
    name: "Moltres",
    "evolution-line": ["Moltres"],
    isEvovable: false,
    type: "fire",
    path: "./pokemon-images/250px-0146Moltres.png",
  },
  {
    id: 147,
    name: "Dratini",
    "evolution-line": ["Dratini", "Dragonair", "Dragonite"],
    "evolution-before": null,
    "evolution-after": "Dragonair",
    isEvovable: true,
    type: "dragon",
    path: "./pokemon-images/250px-0147Dratini.png",
  },
  {
    id: 148,
    name: "Dragonair",
    "evolution-line": ["Dratini", "Dragonair", "Dragonite"],
    "evolution-before": "Dratini",
    "evolution-after": "Dragonite",
    isEvovable: true,
    type: "dragon",
    path: "./pokemon-images/250px-0148Dragonair.png",
  },
  {
    id: 149,
    name: "Dragonite",
    "evolution-line": ["Dratini", "Dragonair", "Dragonite"],
    "evolution-before": "Dragonair",
    "evolution-after": null,
    isEvovable: false,
    type: "dragon",
    path: "./pokemon-images/250px-0149Dragonite.png",
  },
  {
    id: 150,
    name: "Mewtwo",
    "evolution-line": ["Mewtwo"],
    "evolution-before": null,
    "evolution-after": null,
    isEvovable: false,
    type: "psychic",
    path: "./pokemon-images/250px-0150Mewtwo.png",
  },
  {
    id: 151,
    name: "Mew",
    "evolution-line": ["Mew"],
    "evolution-before": null,
    "evolution-after": null,
    isEvovable: false,
    type: "psychic",
    path: "./pokemon-images/250px-0151Mew.png",
  },
];

export default pokemonData;
